POPULAR_PS2_GAMES = [
    {"title": "Grand Theft Auto: San Andreas", "rating": 9.5},
    {"title": "God of War", "rating": 9.4},
    {"title": "God of War II", "rating": 9.5},
    {"title": "Shadow of the Colossus", "rating": 9.2},
    {"title": "Metal Gear Solid 3: Snake Eater", "rating": 9.6},
    {"title": "Final Fantasy X", "rating": 9.0},
    {"title": "Kingdom Hearts", "rating": 8.9},
    {"title": "Kingdom Hearts II", "rating": 9.0},
    {"title": "Resident Evil 4", "rating": 9.6},
    {"title": "Grand Theft Auto: Vice City", "rating": 9.3},
    {"title": "Grand Theft Auto III", "rating": 9.0},
    {"title": "Devil May Cry", "rating": 8.8},
    {"title": "Devil May Cry 3: Dante's Awakening", "rating": 9.0},
    {"title": "Persona 4", "rating": 9.3},
    {"title": "Persona 3 FES", "rating": 9.0},
    {"title": "Okami", "rating": 9.3},
    {"title": "Ratchet & Clank: Up Your Arsenal", "rating": 9.0},
    {"title": "Jak and Daxter: The Precursor Legacy", "rating": 8.8},
    {"title": "Ico", "rating": 8.9},
    {"title": "Tony Hawk's Pro Skater 3", "rating": 9.1},
    {"title": "SSX Tricky", "rating": 8.9},
    {"title": "Guitar Hero II", "rating": 8.8},
    {"title": "Burnout 3: Takedown", "rating": 9.2},
    {"title": "Need for Speed: Most Wanted", "rating": 8.5},
    {"title": "WWE SmackDown! Here Comes the Pain", "rating": 8.7},
    {"title": "Tekken 5", "rating": 8.9},
    {"title": "Soul Calibur III", "rating": 8.7},
    {"title": "Dragon Quest VIII: Journey of the Cursed King", "rating": 9.1},
    {"title": "Silent Hill 2", "rating": 9.5},
    {"title": "Bully", "rating": 8.7},
    {"title": "Final Fantasy XII", "rating": 9.0},
    {"title": "Metal Gear Solid 2: Sons of Liberty", "rating": 9.4},
    {"title": "Resident Evil Code: Veronica X", "rating": 8.5},
    {"title": "Gran Turismo 3: A-Spec", "rating": 9.5},
    {"title": "Gran Turismo 4", "rating": 9.3},
    {"title": "Ratchet & Clank", "rating": 8.9},
    {"title": "Ratchet & Clank: Going Commando", "rating": 9.0},
    {"title": "Jak II: Renegade", "rating": 8.9},
    {"title": "Jak 3", "rating": 8.8},
    {"title": "Sly Cooper and the Thievius Raccoonus", "rating": 8.6},
    {"title": "Sly 2: Band of Thieves", "rating": 8.8},
    {"title": "Sly 3: Honor Among Thieves", "rating": 8.7},
    {"title": "Prince of Persia: The Sands of Time", "rating": 9.2},
    {"title": "Prince of Persia: Warrior Within", "rating": 8.5},
    {"title": "Prince of Persia: The Two Thrones", "rating": 8.6},
    {"title": "Katamari Damacy", "rating": 8.8},
    {"title": "We Love Katamari", "rating": 8.7},
    {"title": "Star Wars: Battlefront II", "rating": 8.6},
    {"title": "TimeSplitters 2", "rating": 8.9},
    {"title": "TimeSplitters: Future Perfect", "rating": 8.8},
    {"title": "Crash Bandicoot: The Wrath of Cortex", "rating": 7.8},
    {"title": "Spyro: Enter the Dragonfly", "rating": 7.2},
    {"title": "Twisted Metal: Black", "rating": 8.8},
    {"title": "Zone of the Enders: The 2nd Runner", "rating": 8.9},
    {"title": "Onimusha: Warlords", "rating": 8.6},
    {"title": "Onimusha 2: Samurai's Destiny", "rating": 8.5},
    {"title": "Onimusha 3: Demon Siege", "rating": 8.4},
    {"title": "Dark Cloud", "rating": 8.3},
    {"title": "Dark Cloud 2", "rating": 8.9},
    {"title": "The Warriors", "rating": 8.5},
    {"title": "Manhunt", "rating": 8.0},
    {"title": "Viewtiful Joe", "rating": 8.8},
    {"title": "Viewtiful Joe 2", "rating": 8.5},
    {"title": "Beyond Good & Evil", "rating": 8.8},
    {"title": "Psychonauts", "rating": 8.9},
    {"title": "Final Fantasy X-2", "rating": 8.0},
    {"title": "Shin Megami Tensei: Nocturne", "rating": 8.7},
    {"title": "Digital Devil Saga", "rating": 8.6},
    {"title": "Digital Devil Saga 2", "rating": 8.7},
    {"title": "Disgaea: Hour of Darkness", "rating": 8.8},
    {"title": "Disgaea 2: Cursed Memories", "rating": 8.6},
    {"title": "Xenosaga Episode I", "rating": 8.3},
    {"title": "Xenosaga Episode II", "rating": 7.9},
    {"title": "Xenosaga Episode III", "rating": 8.5},
    {"title": "Star Ocean: Till the End of Time", "rating": 8.5},
    {"title": "Valkyrie Profile 2: Silmeria", "rating": 8.4},
    {"title": "Radiata Stories", "rating": 8.2},
    {"title": "Rogue Galaxy", "rating": 8.5},
    {"title": "Tales of the Abyss", "rating": 8.7},
    {"title": "Tales of Symphonia", "rating": 8.9},
    {"title": "Suikoden III", "rating": 8.5},
    {"title": "Suikoden V", "rating": 8.6},
    {"title": "Wild Arms 3", "rating": 8.3},
    {"title": "Gradius V", "rating": 8.7},
    {"title": "R-Type Final", "rating": 8.3},
    {"title": "Ace Combat 04: Shattered Skies", "rating": 8.8},
    {"title": "Ace Combat 5: The Unsung War", "rating": 9.0},
    {"title": "Ace Combat Zero: The Belkan War", "rating": 8.8},
    {"title": "SSX 3", "rating": 8.9},
    {"title": "Tony Hawk's Pro Skater 4", "rating": 9.0},
    {"title": "Tony Hawk's Underground", "rating": 8.8},
    {"title": "Tony Hawk's Underground 2", "rating": 8.5},
    {"title": "Burnout Revenge", "rating": 8.8},
    {"title": "Need for Speed: Underground", "rating": 8.6},
    {"title": "Need for Speed: Underground 2", "rating": 8.7},
    {"title": "Need for Speed: Hot Pursuit 2", "rating": 8.4},
    {"title": "Need for Speed: Carbon", "rating": 8.2},
    {"title": "Midnight Club 3: DUB Edition", "rating": 8.5},
    {"title": "Midnight Club II", "rating": 8.3},
    {"title": "Guitar Hero", "rating": 8.7},
    {"title": "Guitar Hero III: Legends of Rock", "rating": 8.6},
    {"title": "Rock Band", "rating": 8.8},
    {"title": "Rock Band 2", "rating": 8.9},
    {"title": "SingStar", "rating": 7.9},
    {"title": "Tekken Tag Tournament", "rating": 8.8},
    {"title": "Tekken 4", "rating": 8.3},
    {"title": "Soul Calibur II", "rating": 9.3},
    {"title": "Mortal Kombat: Deadly Alliance", "rating": 8.3},
    {"title": "Mortal Kombat: Deception", "rating": 8.4},
    {"title": "Mortal Kombat: Armageddon", "rating": 7.8},
    {"title": "Street Fighter Alpha Anthology", "rating": 8.5},
    {"title": "Capcom vs SNK 2", "rating": 8.9},
    {"title": "Marvel vs Capcom 2", "rating": 9.0},
    {"title": "Guilty Gear XX", "rating": 8.8},
    {"title": "King of Fighters XI", "rating": 8.3},
    {"title": "Def Jam: Fight for NY", "rating": 8.6},
    {"title": "WWE SmackDown vs Raw 2006", "rating": 8.5},
    {"title": "WWE SmackDown vs Raw 2007", "rating": 8.4},
    {"title": "Madden NFL 2005", "rating": 8.9},
    {"title": "NBA Street Vol. 2", "rating": 8.8},
    {"title": "NBA Street V3", "rating": 8.5},
    {"title": "FIFA 2005", "rating": 8.6},
    {"title": "Pro Evolution Soccer 5", "rating": 9.0},
    {"title": "Pro Evolution Soccer 6", "rating": 9.1},
    {"title": "NFL Street", "rating": 8.4},
    {"title": "NFL Street 2", "rating": 8.6},
    {"title": "MVP Baseball 2005", "rating": 8.9},
    {"title": "SSX On Tour", "rating": 8.4},
    {"title": "Amplitude", "rating": 8.6},
    {"title": "Frequency", "rating": 8.4},
    {"title": "Baldur's Gate: Dark Alliance", "rating": 8.7},
    {"title": "Baldur's Gate: Dark Alliance II", "rating": 8.6},
    {"title": "Champions of Norrath", "rating": 8.5},
    {"title": "Champions: Return to Arms", "rating": 8.3},
    {"title": "Gauntlet: Dark Legacy", "rating": 8.2},
    {"title": "Spider-Man 2", "rating": 8.5},
    {"title": "The Incredible Hulk: Ultimate Destruction", "rating": 8.3},
    {"title": "X-Men Legends", "rating": 8.4},
    {"title": "X-Men Legends II: Rise of Apocalypse", "rating": 8.6},
    {"title": "The Simpsons: Hit & Run", "rating": 8.1},
    {"title": "Destroy All Humans!", "rating": 8.3},
    {"title": "Destroy All Humans! 2", "rating": 8.4},
    {"title": "Mercenaries: Playground of Destruction", "rating": 8.5},
    {"title": "Freedom Fighters", "rating": 8.5},
    {"title": "SOCOM: U.S. Navy SEALs", "rating": 8.5},
    {"title": "SOCOM II: U.S. Navy SEALs", "rating": 8.7},
    {"title": "SOCOM 3: U.S. Navy SEALs", "rating": 8.5},
    {"title": "Black", "rating": 8.3},
    {"title": "Killzone", "rating": 7.8},
    {"title": "Medal of Honor: Frontline", "rating": 8.8},
    {"title": "Medal of Honor: Rising Sun", "rating": 8.2},
    {"title": "Call of Duty: Finest Hour", "rating": 8.3},
    {"title": "Call of Duty 2: Big Red One", "rating": 8.4},
    {"title": "Call of Duty 3", "rating": 8.1},
    {"title": "Brothers in Arms: Road to Hill 30", "rating": 8.5},
    {"title": "Brothers in Arms: Earned in Blood", "rating": 8.3},
    {"title": "Rainbow Six 3", "rating": 8.4},
    {"title": "Splinter Cell", "rating": 8.9},
    {"title": "Splinter Cell: Pandora Tomorrow", "rating": 8.7},
    {"title": "Splinter Cell: Chaos Theory", "rating": 9.1},
    {"title": "Hitman 2: Silent Assassin", "rating": 8.7},
    {"title": "Hitman: Contracts", "rating": 8.4},
    {"title": "Hitman: Blood Money", "rating": 8.8},
    {"title": "Max Payne", "rating": 8.8},
    {"title": "Max Payne 2: The Fall of Max Payne", "rating": 8.9},
    {"title": "The Getaway", "rating": 8.0},
    {"title": "The Getaway: Black Monday", "rating": 7.8},
    {"title": "Mafia", "rating": 8.6},
    {"title": "The Godfather", "rating": 8.3},
    {"title": "Scarface: The World is Yours", "rating": 8.3},
    {"title": "Saints Row", "rating": 8.2},
    {"title": "True Crime: Streets of LA", "rating": 8.0},
    {"title": "True Crime: New York City", "rating": 7.5},
    {"title": "Fahrenheit (Indigo Prophecy)", "rating": 8.5},
    {"title": "The Suffering", "rating": 8.3},
    {"title": "The Suffering: Ties That Bind", "rating": 8.1},
    {"title": "Fatal Frame", "rating": 8.5},
    {"title": "Fatal Frame II: Crimson Butterfly", "rating": 8.8},
    {"title": "Fatal Frame III: The Tormented", "rating": 8.6},
    {"title": "Silent Hill 3", "rating": 8.9},
    {"title": "Silent Hill 4: The Room", "rating": 7.9},
    {"title": "Silent Hill: Origins", "rating": 7.8},
    {"title": "Haunting Ground", "rating": 8.2},
    {"title": "Clock Tower 3", "rating": 7.5},
    {"title": "Forbidden Siren", "rating": 7.8},
    {"title": "Kuon", "rating": 7.6},
    {"title": "Armored Core 3", "rating": 8.4},
    {"title": "Armored Core: Last Raven", "rating": 8.5},
    {"title": "Dynasty Warriors 3", "rating": 8.3},
    {"title": "Dynasty Warriors 4", "rating": 8.5},
    {"title": "Dynasty Warriors 5", "rating": 8.4},
    {"title": "Samurai Warriors", "rating": 8.2},
    {"title": "Samurai Warriors 2", "rating": 8.3},
    {"title": "Warriors Orochi", "rating": 8.4},
    {"title": "Ys: The Ark of Napishtim", "rating": 8.3},
    {"title": "Atelier Iris: Eternal Mana", "rating": 8.0},
    {"title": "Atelier Iris 2: The Azoth of Destiny", "rating": 8.1},
    {"title": "Shadow Hearts", "rating": 8.5},
    {"title": "Shadow Hearts: Covenant", "rating": 8.8},
    {"title": "Shadow Hearts: From the New World", "rating": 8.3},
    {"title": "Breath of Fire: Dragon Quarter", "rating": 7.8},
    {"title": "Arc the Lad: Twilight of the Spirits", "rating": 8.1},
    {"title": "Grandia II", "rating": 8.6},
    {"title": "Grandia III", "rating": 8.2},
    {"title": "Magna Carta: Tears of Blood", "rating": 7.7},
    {"title": "Steambot Chronicles", "rating": 8.0},
    {"title": "Romancing SaGa: Minstrel Song", "rating": 7.9},
    {"title": "Unlimited SaGa", "rating": 6.8},
    {"title": "La Pucelle: Tactics", "rating": 8.2},
    {"title": "Phantom Brave", "rating": 8.3},
    {"title": "Makai Kingdom: Chronicles of the Sacred Tome", "rating": 8.1},
    {"title": "Soul Nomad & the World Eaters", "rating": 8.2},
    {"title": "Eternal Poison", "rating": 7.8},
    {"title": "GrimGrimoire", "rating": 8.1},
    {"title": "Odin Sphere", "rating": 8.6},
    {"title": "Gungrave", "rating": 8.0},
    {"title": "Gungrave: Overdose", "rating": 8.1},
    {"title": "Blood Will Tell", "rating": 7.9},
    {"title": "Musashi: Samurai Legend", "rating": 7.5},
    {"title": "Genji: Dawn of the Samurai", "rating": 7.8},
    {"title": "Shinobi", "rating": 8.3},
    {"title": "Nightshade", "rating": 7.9},
    {"title": "Tenchu: Wrath of Heaven", "rating": 8.4},
    {"title": "Tenchu: Fatal Shadows", "rating": 7.8},
    {"title": "Way of the Samurai", "rating": 7.6},
    {"title": "Way of the Samurai 2", "rating": 7.9},
    {"title": "Kessen", "rating": 7.8},
    {"title": "Kessen II", "rating": 7.7},
    {"title": "Kessen III", "rating": 8.0},
    {"title": "Ring of Red", "rating": 7.9},
    {"title": "Front Mission 4", "rating": 8.4},
    {"title": "Front Mission 5: Scars of the War", "rating": 8.3},
    {"title": "Growlanser Generations", "rating": 7.8},
    {"title": "Growlanser: Heritage of War", "rating": 7.6},
    {"title": "Sakura Wars: So Long, My Love", "rating": 8.2},
    {"title": "Ar tonelico: Melody of Elemia", "rating": 8.0},
    {"title": "Ar tonelico II: Melody of Metafalica", "rating": 8.2},
    {"title": "Drakengard", "rating": 7.7},
    {"title": "Drakengard 2", "rating": 7.5},
    {"title": "Chaos Legion", "rating": 7.4},
    {"title": "Crimson Tears", "rating": 6.9},
    {"title": "Seven Samurai 20XX", "rating": 7.3},
    {"title": "Rygar: The Legendary Adventure", "rating": 7.8},
    {"title": "Maximo: Ghosts to Glory", "rating": 8.1},
    {"title": "Maximo vs. Army of Zin", "rating": 7.8},
    {"title": "Klonoa 2: Lunatea's Veil", "rating": 8.5},
    {"title": "Rayman 2: Revolution", "rating": 8.3},
    {"title": "Rayman 3: Hoodlum Havoc", "rating": 8.1},
    {"title": "Rayman Raving Rabbids", "rating": 7.8},
    {"title": "Rayman Arena", "rating": 7.5},
    {"title": "Ty the Tasmanian Tiger", "rating": 7.6},
    {"title": "Ty the Tasmanian Tiger 2", "rating": 7.4},
    {"title": "Tak and the Power of Juju", "rating": 7.5},
    {"title": "Tak 2: The Staff of Dreams", "rating": 7.3},
    {"title": "Vexx", "rating": 7.4},
    {"title": "Whiplash", "rating": 7.2},
    {"title": "Sphinx and the Cursed Mummy", "rating": 8.0},
    {"title": "I-Ninja", "rating": 7.8},
    {"title": "Pac-Man World 2", "rating": 7.7},
    {"title": "Pac-Man World 3", "rating": 7.2},
    {"title": "Oddworld: Munch's Oddysee", "rating": 8.0},
    {"title": "Oddworld: Stranger's Wrath", "rating": 8.6},
    {"title": "Primal", "rating": 8.1},
    {"title": "Mark of Kri", "rating": 8.2},
    {"title": "Rise of the Kasai", "rating": 7.5},
    {"title": "Shinobi", "rating": 8.3},
    {"title": "Blood Omen 2: Legacy of Kain", "rating": 7.8},
    {"title": "Legacy of Kain: Defiance", "rating": 8.2},
    {"title": "Soul Reaver 2", "rating": 8.4},
    {"title": "Castlevania: Lament of Innocence", "rating": 8.3},
    {"title": "Castlevania: Curse of Darkness", "rating": 8.1},
    {"title": "Ninja Gaiden", "rating": 9.2},
    {"title": "Ninja Gaiden Black", "rating": 9.3},
    {"title": "Mortal Kombat: Shaolin Monks", "rating": 8.5},
    {"title": "God Hand", "rating": 8.4},
    {"title": "Beatdown: Fists of Vengeance", "rating": 6.5},
    {"title": "Urban Reign", "rating": 7.9},
    {"title": "The Red Star", "rating": 7.8},
    {"title": "Metal Slug Anthology", "rating": 8.4},
    {"title": "Metal Slug 3", "rating": 8.7},
    {"title": "Contra: Shattered Soldier", "rating": 7.8},
    {"title": "Neo Contra", "rating": 7.3},
    {"title": "Tron 2.0: Killer App", "rating": 7.6},
    {"title": "Enter the Matrix", "rating": 6.8},
    {"title": "The Matrix: Path of Neo", "rating": 7.5},
    {"title": "BloodRayne", "rating": 7.8},
    {"title": "BloodRayne 2", "rating": 7.6},
    {"title": "Van Helsing", "rating": 7.2},
    {"title": "Constantine", "rating": 7.0},
    {"title": "The Chronicles of Riddick: Escape from Butcher Bay", "rating": 8.9},
    {"title": "The Punisher", "rating": 8.1},
    {"title": "Spawn: Armageddon", "rating": 7.0},
    {"title": "Hulk", "rating": 7.5},
    {"title": "Ultimate Spider-Man", "rating": 8.3},
    {"title": "Spider-Man 3", "rating": 7.2},
    {"title": "Fantastic Four", "rating": 6.8},
    {"title": "X2: Wolverine's Revenge", "rating": 7.4},
    {"title": "Batman Begins", "rating": 7.8},
    {"title": "Batman: Rise of Sin Tzu", "rating": 7.3},
    {"title": "Superman: Shadow of Apokolips", "rating": 6.5},
    {"title": "Justice League Heroes", "rating": 7.8},
    {"title": "Teen Titans", "rating": 7.2},
    {"title": "Teenage Mutant Ninja Turtles", "rating": 7.5},
    {"title": "Teenage Mutant Ninja Turtles 2: Battle Nexus", "rating": 7.3},
    {"title": "Teenage Mutant Ninja Turtles 3: Mutant Nightmare", "rating": 7.0},
    {"title": "Power Rangers: Dino Thunder", "rating": 6.8},
    {"title": "Transformers", "rating": 7.5},
    {"title": "Transformers: The Game", "rating": 7.3},
    {"title": "G.I. Joe: The Rise of Cobra", "rating": 6.9},
    {"title": "Avatar: The Last Airbender", "rating": 7.4},
    {"title": "Avatar: The Last Airbender - The Burning Earth", "rating": 7.2},
    {"title": "Naruto: Ultimate Ninja", "rating": 7.8},
    {"title": "Naruto: Ultimate Ninja 2", "rating": 8.0},
    {"title": "Naruto: Ultimate Ninja 3", "rating": 8.2},
    {"title": "Naruto: Uzumaki Chronicles", "rating": 7.5},
    {"title": "Naruto: Uzumaki Chronicles 2", "rating": 7.6},
    {"title": "Dragon Ball Z: Budokai", "rating": 8.2},
    {"title": "Dragon Ball Z: Budokai 2", "rating": 7.9},
    {"title": "Dragon Ball Z: Budokai 3", "rating": 8.6},
    {"title": "Dragon Ball Z: Budokai Tenkaichi", "rating": 8.3},
    {"title": "Dragon Ball Z: Budokai Tenkaichi 2", "rating": 8.5},
    {"title": "Dragon Ball Z: Budokai Tenkaichi 3", "rating": 8.7},
    {"title": "Dragon Ball Z: Sagas", "rating": 6.5},
    {"title": "Dragon Ball Z: Infinite World", "rating": 7.8},
    {"title": "Bleach: Blade Battlers", "rating": 7.6},
    {"title": "Bleach: Blade Battlers 2nd", "rating": 7.7},
    {"title": "One Piece: Grand Adventure", "rating": 7.8},
    {"title": "One Piece: Grand Battle", "rating": 7.5},
    {"title": "Fullmetal Alchemist and the Broken Angel", "rating": 7.4},
    {"title": "Fullmetal Alchemist 2: Curse of the Crimson Elixir", "rating": 7.6},
    {"title": "InuYasha: The Secret of the Cursed Mask", "rating": 7.2},
    {"title": "Samurai Champloo: Sidetracked", "rating": 7.5},
    {"title": "Cowboy Bebop", "rating": 7.3},
    {"title": "Neon Genesis Evangelion 2", "rating": 7.4},
    {"title": "Mobile Suit Gundam: Journey to Jaburo", "rating": 7.6},
    {"title": "Mobile Suit Gundam: Encounters in Space", "rating": 7.8},
    {"title": "Mobile Suit Gundam Seed", "rating": 7.5},
    {"title": "Zoids: Battle Legends", "rating": 7.3},
    {"title": "Yu-Gi-Oh! The Duelists of the Roses", "rating": 7.6},
    {"title": "Yu-Gi-Oh! Capsule Monster Coliseum", "rating": 7.2},
    {"title": "Shaman King: Power of Spirit", "rating": 7.1},
    {"title": "Mega Man X7", "rating": 6.8},
    {"title": "Mega Man X8", "rating": 7.9},
    {"title": "Mega Man X: Command Mission", "rating": 7.7},
    {"title": "Mega Man Anniversary Collection", "rating": 8.3},
    {"title": "Mega Man X Collection", "rating": 8.5},
    {"title": "Castlevania: Symphony of the Night", "rating": 9.4},
    {"title": "Contra: Legacy of War", "rating": 6.5},
    {"title": "Syphon Filter: The Omega Strain", "rating": 8.2},
    {"title": "Syphon Filter: Dark Mirror", "rating": 8.4},
    {"title": "Conflict: Desert Storm", "rating": 8.0},
    {"title": "Conflict: Desert Storm II", "rating": 8.1},
    {"title": "Conflict: Vietnam", "rating": 7.8},
    {"title": "Conflict: Global Terror", "rating": 7.5},
    {"title": "Delta Force: Black Hawk Down", "rating": 7.9},
    {"title": "Full Spectrum Warrior", "rating": 8.2},
    {"title": "Full Spectrum Warrior: Ten Hammers", "rating": 7.8},
    {"title": "Ghost Recon", "rating": 8.3},
    {"title": "Ghost Recon 2", "rating": 8.1},
    {"title": "Ghost Recon: Jungle Storm", "rating": 7.9},
    {"title": "Army Men: Sarge's War", "rating": 7.0},
    {"title": "Men of Valor", "rating": 7.6},
    {"title": "Shellshock: Nam '67", "rating": 7.2},
    {"title": "Battlefield 2: Modern Combat", "rating": 8.0},
    {"title": "Area 51", "rating": 7.5},
    {"title": "The Thing", "rating": 7.9},
    {"title": "Cold Fear", "rating": 7.6},
    {"title": "Dino Crisis 3", "rating": 6.8},
    {"title": "Extermination", "rating": 7.4},
    {"title": "Siren 2", "rating": 7.9},
    {"title": "Rule of Rose", "rating": 7.7},
    {"title": "Obscure", "rating": 7.5},
    {"title": "Obscure II", "rating": 7.3},
    {"title": "Nightmares & Dreamscapes", "rating": 6.8},
]